name: MLops Pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Train Model
        run: |
          python scripts/train.py

      - name: Validate Model
        run: |
          python scripts/validate.py

      - name: Sync with Hugging Face Spaces
        uses: nateraw/huggingface-sync-action@v0.0.4
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          hf_repo: Prahmodh/iris-classification-app
          hf_path: .
